// <auto-generated />
namespace PorticoRegistration.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EnhancedPatientPoco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnhancedPatientPoco));
        
        string IMigrationMetadata.Id
        {
            get { return "201506012041118_EnhancedPatientPoco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
